name: Run TestNG Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Alternative: 'zulu', 'adopt', etc.
          java-version: '17'
          cache: 'maven'

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run TestNG Tests
        run: mvn test

      - name: Upload Test Reports
        if: always()  # Ensures reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/
